Category Tracker feature
MarcusNkadimeng/my-Budget-App pull request #10
Opened 2024-05-17 15:59 UTC by MarcusNkadimeng

[Merge]

[Merge] feature/categories → Develop 
[Feature] - Category Tracker screen
 
 ## Description 
Created a category tracking feature which groups categories into their respective category groups (e.g., Rent and WiFi would be in the Bills category group).
 
## Screenshots/GIFs 
![Screen Recording 2024-05-17 at 17 55 37](https://github.com/MarcusNkadimeng/my-Budget-App/assets/164848888/67b93992-5f73-49bb-8b4a-947a238ce5c0)
 
## Checklist 
Please review and check the following before submitting this pull request: 
- [ ] The code follows the project's coding standards. 
- [ ] 100% Unit test coverage for View Models 
- [ ] All warnings Resolved.

2024-05-17 19:41 UTC, kieran-woodrow requested changes

2024-05-17 19:41 UTC, kieran-woodrow commented on budgetApp1/budgetApp1/AccountViewCell.swift
> +        self.separatorInset = UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)
no need for sef

2024-05-17 19:41 UTC, kieran-woodrow commented on budgetApp1/budgetApp1/CategoryTrackerViewModel.swift
> +
new line

2024-05-17 19:41 UTC, kieran-woodrow commented on budgetApp1/budgetApp1/Constants.swift
> +    static let CategoryScreenHeader = "Category Tracker"
small name for variables please

2024-05-17 19:41 UTC, kieran-woodrow commented on budgetApp1/budgetApp1/TrackerViewController.swift
> +        tableView.layer.cornerRadius = 16
this can be done in the storyboard

2024-05-17 19:41 UTC, kieran-woodrow commented on budgetApp1/budgetApp1/TrackerViewController.swift
> +           indexPath.row < categories.count {
this is logic that belongs in the viewmodel

2024-05-23 11:22 UTC, kieran-woodrow approved these changes
Good job with the PR👏🏼

2024-05-23 15:15 UTC, giacatano approved these changes

2024-05-23 17:27 UTC, merged